### ISSUE TITLE
Cannot create database with createF1db()

### ISSUE THREAD

**Issue by IsaacVegaM** [arkraieski/formula1data#8]
When running the example:
`con <- createF1db()`

I get the following error: 
Error: Mapped vectors must have consistent lengths:
* `.x` has length 14
* `.y` has length 13

Also tried  with:
`con <- createF1db(type = "sqlite")`

And got this error:
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'an integer', got '\N'
In addition: Warning messages:
1: Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this. 
2: Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this. 
3: Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this.

**Comment by arkraieski** [comment]
Hi there! I'm guessing you have version 0.1.0 of the package installed currently? I merged a fix for this a few days ago, actually. Please reinstall the package (should get you version 0.1.1) and retry. Either value for _type_ should be ok now too. That should fix things, but admittedly I've only tested that on Windows so far.

[Issue 6](https://github.com/arkraieski/formula1data/issues/6) (now closed) has some more info. All of that code is merged into the master branch now. I probably need to refactor the function some to handle any future data schema additions/changes in a more helpful/robust way.

Regarding those last 3 warnings, I think that's suggesting that I should set the _shutdown=TRUE_ argument when disconnecting from the database in the error-handling code for the function, so I will look into that as well.

Thanks for taking the time to report this here!

**Comment by IsaacVegaM** [comment]
Thank you for the response! In fact, I did not have version 0.1.1 installed.  Now the function works as expected! 
I will continue to test and if something else happens I will let you know.

Cheers

**Comment by arkraieski** [comment]
Awesome, glad to hear it!
